# Static analysis allows you to find problems before executing a single line of code.
# You may customize the Analysis Options by following this guide:
# https://dart.dev/guides/language/analysis-options
